[versions]
activity="1.10.1"
activityKtx="1.10.1"
aspectjtools="1.9.25"
adapterRxjava2="3.0.0"
asynclayoutinflater="1.1.0"
coilVersion="2.7.0"
composeBom="2025.11.01"
coreTesting="2.2.0"
eventbus="3.3.1"
fragmentKtx="1.8.9"
glideVersion="4.13.2"
lifecycleExtensions="2.2.0"
minSdk="27"
okhttp3Integration="5.0.5"
okhttpBom="5.3.2"
reactivexRxandroid="2.1.1"
reactivexRxjava="2.2.21"
rxandroidVersion="3.0.2"
rxjavaVersion="3.1.8"
swiperefreshlayout="1.1.0"
targetSdk="29"
androidGradlePlugin = "8.13.1"
arrow = "2.2.0"
glide = "5.0.5"
kotlin_verison = "2.2.21"
gson = "2.13.2"
retrofit = "3.0.0"
cardview = "1.0.0"
okhttp="5.3.2"
okio= "3.16.2"
coroutine= "1.10.2"
androidx-core-ktx="1.16.0"
androidx-work-ktx="2.11.0"
androidx-viewpager2="1.1.0"
androidx-appcompat-appcompat="1.7.1"
androidx-activity-ktx="1.9.0"
android-material="1.13.0"
constraintLayout="2.2.1"
coordinateLayout="1.3.0"
lifecycle="2.10.0"
hilt_version= "2.57.2"
coil = "2.7.0"
androidxHiltNavigationCompose = "1.3.0"
hilt = "2.57.2"
hiltExt = "1.3.0"
recyclerview="1.4.0"
junit4 = "4.13.2"
androixJunit="1.2.1"
espresso="3.7.0"
rxandroid = "3.0.2"
rxjava = "3.1.12"
slfj="2.0.17"
ultraPtr="1.0.11"
x_crash="3.1.0"
slfj-android="1.7.36"
oboe_version="1.10.0"
kspversion="2.3.3"

kotlinxDatetime = "0.7.1-0.6.x-compat"
kotlinxSerializationJson = "1.9.0"
ktor = "1.6.3"
exfiinterface="1.4.1"
#exoplayer = "2.19.1"
media3_version ="1.8.0"
camerax_version="1.5.1"
compiler="1.5.15"

room = "2.8.4"

kotlinxCollectionsImmutable = "0.4.0"
mmkv = "2.2.4"
material3Android = "1.4.0"
material3 = "1.3.2"
# other versions

[libraries]
adapter-rxjava2 = { module = "com.squareup.retrofit2:adapter-rxjava2", version.ref = "adapterRxjava2" }
adapter-rxjava3 = { module = "com.squareup.retrofit2:adapter-rxjava3", version.ref = "retrofit" }
android-gradle-build-plugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "activity" }
androidx-activity-ktx= { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-asynclayoutinflater = { module = "androidx.asynclayoutinflater:asynclayoutinflater", version.ref = "asynclayoutinflater" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compiler" }
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }
androidx-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycleExtensions" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }
androidx-lifecycle-reactivestreams = { module = "androidx.lifecycle:lifecycle-reactivestreams", version.ref = "lifecycle" }
androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "lifecycle" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
arrow-optics = { module = "io.arrow-kt:arrow-optics", version.ref = "arrow" }
arrow-opticsreflect = { module = "io.arrow-kt:arrow-optics-reflect", version.ref = "arrow" }
arrow-resilience = { module = "io.arrow-kt:arrow-resilience", version.ref = "arrow" }
arrow-atomic = { module = "io.arrow-kt:arrow-atomic", version.ref = "arrow" }
arrow-fx-stm-jvm = { module = "io.arrow-kt:arrow-fx-stm-jvm", version.ref = "arrow" }
arrow-fx-coroutines = { module = "io.arrow-kt:arrow-fx-coroutines", version.ref = "arrow" }
aspectjtools = { module = "org.aspectj:aspectjtools", version.ref = "aspectjtools" }
coil-v240 = { module = "io.coil-kt:coil", version.ref = "coilVersion" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
eventbus = { module = "org.greenrobot:eventbus", version.ref = "eventbus" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
glide-ksp = { module = "com.github.bumptech.glide:ksp", version.ref = "glide" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin_verison" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin_verison" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin_verison" }
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttpBom" }
okhttp3-integration = { module = "com.github.bumptech.glide:okhttp3-integration", version.ref = "okhttp3Integration" }
retrofit = {  module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit"  }
arrow-integration-retrofit = { module = "io.arrow-kt:arrow-core-retrofit", version.ref = "arrow" }
arrow-opticsksp-plugin = { module = "io.arrow-kt:arrow-optics-ksp-plugin", version.ref = "arrow" }
oboe = { module = "com.google.oboe:oboe", version.ref = "oboe_version" }



androidx-work-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work-ktx" }
androidx-core-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
androidx-viewpager2-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "androidx-viewpager2" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
androidx-coordinatelayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "coordinateLayout" }
androidx-recyclerview-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-appcompat-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat-appcompat" }
google-android-material-material = { module = "com.google.android.material:material", version.ref = "android-material" }
androidx-cardview-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
androidx-exfi-interface = { module = "androidx.exifinterface:exifinterface", version.ref = "exfiinterface" }
##ViewModelScope
androidx-lifecycle-lifecycle-viewmodel-ktx  = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
##LifecycleScope
androidx-lifecycle-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
##LiveData
androidx-lifecycle-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-datastore-core= { module = "androidx.datastore:datastore-preferences-core", version = "1.2.0" }
androidx-datastore-preference = { module = "androidx.datastore:datastore-preferences", version = "1.2.0" }

google-dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt_version" }
google-dagger-hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt_version" }
google-dagger-hilt-build-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt_version" }
iqiyi-xcrash = { module = "com.iqiyi.xcrash:xcrash-android-lib", version.ref = "x_crash" }

##camerax
camerax-camera-core = { module = "androidx.camera:camera-core", version.ref = "camerax_version" }
camerax-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camerax_version" }
camerax-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camerax_version" }
camerax-camera-video = { module = "androidx.camera:camera-video", version.ref = "camerax_version" }
camerax-camera-view = { module = "androidx.camera:camera-view", version.ref = "camerax_version" }
camerax-camera-extensions = { module = "androidx.camera:camera-extensions", version.ref = "camerax_version" }

#Image loading
coil-kt-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
coil-kt = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-video-kt = { group = "io.coil-kt", name = "coil-video", version.ref = "coil" }
#Dependency injection
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-ext-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltExt" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }

#Kotlin Immutable Collections
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
kotlin-stdlib-java8 = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin_verison" }

#Kotlin Coroutines, serialization, datetime...
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutine" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutine" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

#Database
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

#MMKV
mmkv = { group = "com.tencent", name = "mmkv", version.ref = "mmkv" }

#OkHttp and Retrofit
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }


#ExoPlayer
exoplayer-core = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3_version" }
exoplayer-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3_version" }
exoplayer-dash = { group = "androidx.media3", name = "media3-exoplayer-dash", version.ref = "media3_version" }
exoplayer-hls = { group = "androidx.media3", name = "media3-exoplayer-hls", version.ref = "media3_version" }
#exoplayer-smoothstreaming = { group = "com.google.android.exoplayer", name = "exoplayer-smoothstreaming", version.ref = "exoplayer" }
#exoplayer-cast = { group = "com.google.android.exoplayer", name = "exoplayer-cast", version.ref = "exoplayer" }
#exoplayer-extension-mediasession = { group = "com.google.android.exoplayer", name = "extension-mediasession", version.ref = "exoplayer" }

# testsuite
junit-junit = { group = "junit", name = "junit", version.ref = "junit4" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androixJunit" }
androidx-test-espresso-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
rxandroid3 = { module = "io.reactivex.rxjava3:rxandroid", version.ref = "rxandroid" }
rxjava3 = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava" }

# other dependencies
## lfj
rxjava2-rxandroid = { module = "io.reactivex.rxjava2:rxandroid", version.ref = "reactivexRxandroid" }
rxjava2-rxjava = { module = "io.reactivex.rxjava2:rxjava", version.ref = "reactivexRxjava" }
slfj-api = { module = "org.slf4j:slf4j-api", version.ref = "slfj" }
slfj-android = { module = "org.slf4j:slf4j-android", version.ref = "slfj-android" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }
ultra-ptr = { module = "in.srain.cube:ultra-ptr", version.ref = "ultraPtr" }




[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin_verison" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin_verison" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin_verison" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin_verison" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kspversion" }

